export const chemicalElements = [
  {
    element: "H",
    name: "Hydrogen",
    atomicNumber: 1,
    atomicMass: 1.008,
    group: 1,
    period: 1,
    block: "s",
    state: "gas",
    symbol: "H",
    electronConfig: "1s1",
    electronegativity: 2.2,
    atomicRadius: 37,
    ionRadius: "",
    vanDelWaalsRadius: 120,
    ionizationEnergy: 1312,
    electronAffinity: -73,
    oxidationStates: "-1, 1",
    standardState: "gas",
    bondingType: "diatomic",
    meltingPoint: 14,
    boilingPoint: 20,
    density: 0.00008988,
    groupBlock: "nonmetal",
    yearDiscovered: 1766,
    electronsPerShell: [1],
  },
  {
    element: "He",
    name: "Helium",
    atomicNumber: 2,
    atomicMass: 4.002602,
    group: 18,
    period: 1,
    block: "s",
    state: "gas",
    symbol: "He",
    electronConfig: "1s2",
    electronegativity: "",
    atomicRadius: 32,
    ionRadius: "",
    vanDelWaalsRadius: 140,
    ionizationEnergy: 2372,
    electronAffinity: 0,
    oxidationStates: "",
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: "",
    boilingPoint: 4,
    density: 0.0001785,
    groupBlock: "noble gas",
    yearDiscovered: 1868,
    electronsPerShell: [2],
  },
  {
    element: "Li",
    name: "Lithium",
    atomicNumber: 3,
    atomicMass: 6.94,
    group: 1,
    period: 2,
    block: "s",
    state: "solid",
    symbol: "Li",
    electronConfig: "[He] 2s1",
    electronegativity: 0.98,
    atomicRadius: 134,
    ionRadius: "76 (+1)",
    vanDelWaalsRadius: 182,
    ionizationEnergy: 520,
    electronAffinity: -60,
    oxidationStates: 1,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 454,
    boilingPoint: 1615,
    density: 0.534,
    groupBlock: "alkali metal",
    yearDiscovered: 1817,
    electronsPerShell: [2, 1],
  },
  {
    element: "Be",
    name: "Beryllium",
    atomicNumber: 4,
    atomicMass: 9.0121831,
    group: 2,
    period: 2,
    block: "s",
    state: "solid",
    symbol: "Be",
    electronConfig: "[He] 2s2",
    electronegativity: 1.57,
    atomicRadius: 90,
    ionRadius: "45 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 900,
    electronAffinity: 0,
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1560,
    boilingPoint: 2742,
    density: 1.85,
    groupBlock: "alkaline earth metal",
    yearDiscovered: 1798,
    electronsPerShell: [2, 2],
  },
  {
    element: "B",
    name: "Boron",
    atomicNumber: 5,
    atomicMass: 10.81,
    group: 13,
    period: 2,
    block: "p",
    state: "solid",
    symbol: "B",
    electronConfig: "[He] 2s2 2p1",
    electronegativity: 2.04,
    atomicRadius: 82,
    ionRadius: "27 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 801,
    electronAffinity: -27,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "covalent network",
    meltingPoint: 2348,
    boilingPoint: 4273,
    density: 2.34,
    groupBlock: "metalloid",
    yearDiscovered: 1807,
    electronsPerShell: [2, 3],
  },
  {
    element: "C",
    name: "Carbon",
    atomicNumber: 6,
    atomicMass: 12.011,
    group: 14,
    period: 2,
    block: "p",
    state: "solid",
    symbol: "C",
    electronConfig: "[He] 2s2 2p2",
    electronegativity: 2.55,
    atomicRadius: 77,
    ionRadius: "16 (+4)",
    vanDelWaalsRadius: 170,
    ionizationEnergy: 1087,
    electronAffinity: -154,
    oxidationStates: "-4, -3, -2, -1, 1, 2, 3, 4",
    standardState: "solid",
    bondingType: "covalent network",
    meltingPoint: 3823,
    boilingPoint: 4300,
    density: 2.26,
    groupBlock: "nonmetal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 4],
  },
  {
    element: "N",
    name: "Nitrogen",
    atomicNumber: 7,
    atomicMass: 14.007,
    group: 15,
    period: 2,
    block: "p",
    state: "gas",
    symbol: "N",
    electronConfig: "[He] 2s2 2p3",
    electronegativity: 3.04,
    atomicRadius: 75,
    ionRadius: "146 (-3)",
    vanDelWaalsRadius: 155,
    ionizationEnergy: 1402,
    electronAffinity: -7,
    oxidationStates: "-3, -2, -1, 1, 2, 3, 4, 5",
    standardState: "gas",
    bondingType: "diatomic",
    meltingPoint: 63,
    boilingPoint: 77,
    density: 0.001251,
    groupBlock: "nonmetal",
    yearDiscovered: 1772,
    electronsPerShell: [2, 5],
  },
  {
    element: "O",
    name: "Oxygen",
    atomicNumber: 8,
    atomicMass: 15.999,
    group: 16,
    period: 2,
    block: "p",
    state: "gas",
    symbol: "O",
    electronConfig: "[He] 2s2 2p4",
    electronegativity: 3.44,
    atomicRadius: 73,
    ionRadius: "140 (-2)",
    vanDelWaalsRadius: 152,
    ionizationEnergy: 1314,
    electronAffinity: -141,
    oxidationStates: "-2, -1, 1, 2",
    standardState: "gas",
    bondingType: "diatomic",
    meltingPoint: 55,
    boilingPoint: 90,
    density: 0.001429,
    groupBlock: "nonmetal",
    yearDiscovered: 1774,
    electronsPerShell: [2, 6],
  },
  {
    element: "F",
    name: "Fluorine",
    atomicNumber: 9,
    atomicMass: 18.998403163,
    group: 17,
    period: 2,
    block: "p",
    state: "gas",
    symbol: "F",
    electronConfig: "[He] 2s2 2p5",
    electronegativity: 3.98,
    atomicRadius: 71,
    ionRadius: "133 (-1)",
    vanDelWaalsRadius: 147,
    ionizationEnergy: 1681,
    electronAffinity: -328,
    oxidationStates: -1,
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: 54,
    boilingPoint: 85,
    density: 0.001696,
    groupBlock: "halogen",
    yearDiscovered: 1670,
    electronsPerShell: [2, 7],
  },
  {
    element: "Ne",
    name: "Neon",
    atomicNumber: 10,
    atomicMass: 20.1797,
    group: 18,
    period: 2,
    block: "p",
    state: "gas",
    symbol: "Ne",
    electronConfig: "[He] 2s2 2p6",
    electronegativity: "",
    atomicRadius: 69,
    ionRadius: "",
    vanDelWaalsRadius: 154,
    ionizationEnergy: 2081,
    electronAffinity: 0,
    oxidationStates: "",
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: 25,
    boilingPoint: 27,
    density: 0.0009,
    groupBlock: "noble gas",
    yearDiscovered: 1898,
    electronsPerShell: [2, 8],
  },
  {
    element: "Na",
    name: "Sodium",
    atomicNumber: 11,
    atomicMass: 22.98976928,
    group: 1,
    period: 3,
    block: "s",
    state: "solid",
    symbol: "Na",
    electronConfig: "[Ne] 3s1",
    electronegativity: 0.93,
    atomicRadius: 154,
    ionRadius: "102 (+1)",
    vanDelWaalsRadius: 227,
    ionizationEnergy: 496,
    electronAffinity: -53,
    oxidationStates: 1,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 371,
    boilingPoint: 1156,
    density: 0.968,
    groupBlock: "alkali metal",
    yearDiscovered: 1807,
    electronsPerShell: [2, 8, 1],
  },
  {
    element: "Mg",
    name: "Magnesium",
    atomicNumber: 12,
    atomicMass: 24.305,
    group: 2,
    period: 3,
    block: "s",
    state: "solid",
    symbol: "Mg",
    electronConfig: "[Ne] 3s2",
    electronegativity: 1.31,
    atomicRadius: 130,
    ionRadius: "72 (+2)",
    vanDelWaalsRadius: 173,
    ionizationEnergy: 738,
    electronAffinity: 0,
    oxidationStates: "1, 2",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 923,
    boilingPoint: 1363,
    density: 1.738,
    groupBlock: "alkaline earth metal",
    yearDiscovered: 1808,
    electronsPerShell: [2, 8, 2],
  },
  {
    element: "Al",
    name: "Aluminum",
    atomicNumber: 13,
    atomicMass: 26.9815385,
    group: 13,
    period: 3,
    block: "p",
    state: "solid",
    symbol: "Al",
    electronConfig: "[Ne] 3s2 3p1",
    electronegativity: 1.61,
    atomicRadius: 118,
    ionRadius: "53.5 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 578,
    electronAffinity: -44,
    oxidationStates: "1, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 933,
    boilingPoint: 2792,
    density: 2.7,
    groupBlock: "metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 3],
  },
  {
    element: "Si",
    name: "Silicon",
    atomicNumber: 14,
    atomicMass: 28.085,
    group: 14,
    period: 3,
    block: "p",
    state: "solid",
    symbol: "Si",
    electronConfig: "[Ne] 3s2 3p2",
    electronegativity: 1.9,
    atomicRadius: 111,
    ionRadius: "40 (+4)",
    vanDelWaalsRadius: 210,
    ionizationEnergy: 787,
    electronAffinity: -134,
    oxidationStates: "-4, -3, -2, -1, 1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1687,
    boilingPoint: 3173,
    density: 2.33,
    groupBlock: "metalloid",
    yearDiscovered: 1854,
    electronsPerShell: [2, 8, 4],
  },
  {
    element: "P",
    name: "Phosphorus",
    atomicNumber: 15,
    atomicMass: 30.973762,
    group: 15,
    period: 3,
    block: "p",
    state: "solid",
    symbol: "P",
    electronConfig: "[Ne] 3s2 3p3",
    electronegativity: 2.19,
    atomicRadius: 106,
    ionRadius: "44 (+3)",
    vanDelWaalsRadius: 180,
    ionizationEnergy: 1012,
    electronAffinity: -72,
    oxidationStates: "-3, -2, -1, 1, 2, 3, 4, 5",
    standardState: "solid",
    bondingType: "covalent network",
    meltingPoint: 317,
    boilingPoint: 554,
    density: 1.823,
    groupBlock: "nonmetal",
    yearDiscovered: 1669,
    electronsPerShell: [2, 8, 5],
  },
  {
    element: "S",
    name: "Sulfur",
    atomicNumber: 16,
    atomicMass: 32.06,
    group: 16,
    period: 3,
    block: "p",
    state: "solid",
    symbol: "S",
    electronConfig: "[Ne] 3s2 3p4",
    electronegativity: 2.58,
    atomicRadius: 102,
    ionRadius: "184 (-2)",
    vanDelWaalsRadius: 180,
    ionizationEnergy: 1000,
    electronAffinity: -200,
    oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "covalent network",
    meltingPoint: 388,
    boilingPoint: 718,
    density: 1.96,
    groupBlock: "nonmetal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 6],
  },
  {
    element: "Cl",
    name: "Chlorine",
    atomicNumber: 17,
    atomicMass: 35.45,
    group: 17,
    period: 3,
    block: "p",
    state: "gas",
    symbol: "Cl",
    electronConfig: "[Ne] 3s2 3p5",
    electronegativity: 3.16,
    atomicRadius: 99,
    ionRadius: "181 (-1)",
    vanDelWaalsRadius: 175,
    ionizationEnergy: 1251,
    electronAffinity: -349,
    oxidationStates: "-1, 1, 2, 3, 4, 5, 6, 7",
    standardState: "gas",
    bondingType: "covalent network",
    meltingPoint: 172,
    boilingPoint: 239,
    density: 0.003214,
    groupBlock: "halogen",
    yearDiscovered: 1774,
    electronsPerShell: [2, 8, 7],
  },
  {
    element: "Ar",
    name: "Argon",
    atomicNumber: 18,
    atomicMass: 39.948,
    group: 18,
    period: 3,
    block: "p",
    state: "gas",
    symbol: "Ar",
    electronConfig: "[Ne] 3s2 3p6",
    electronegativity: "",
    atomicRadius: 97,
    ionRadius: "",
    vanDelWaalsRadius: 188,
    ionizationEnergy: 1521,
    electronAffinity: 0,
    oxidationStates: "",
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: 84,
    boilingPoint: 87,
    density: 0.001784,
    groupBlock: "noble gas",
    yearDiscovered: 1894,
    electronsPerShell: [2, 8, 8],
  },
  {
    element: "K",
    name: "Potassium",
    atomicNumber: 19,
    atomicMass: 39.0983,
    group: 1,
    period: 4,
    block: "s",
    state: "solid",
    symbol: "K",
    electronConfig: "[Ar] 4s1",
    electronegativity: 0.82,
    atomicRadius: 196,
    ionRadius: "138 (+1)",
    vanDelWaalsRadius: 275,
    ionizationEnergy: 419,
    electronAffinity: -48,
    oxidationStates: 1,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 337,
    boilingPoint: 1032,
    density: 0.856,
    groupBlock: "alkali metal",
    yearDiscovered: 1807,
    electronsPerShell: [2, 8, 8, 1],
  },
  {
    element: "Ca",
    name: "Calcium",
    atomicNumber: 20,
    atomicMass: 40.078,
    group: 2,
    period: 4,
    block: "s",
    state: "solid",
    symbol: "Ca",
    electronConfig: "[Ar] 4s2",
    electronegativity: 1,
    atomicRadius: 174,
    ionRadius: "100 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 590,
    electronAffinity: -2,
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1115,
    boilingPoint: 1757,
    density: 1.55,
    groupBlock: "alkaline earth metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 8, 2],
  },
  {
    element: "Sc",
    name: "Scandium",
    atomicNumber: 21,
    atomicMass: 44.955908,
    group: 3,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Sc",
    electronConfig: "[Ar] 3d1 4s2",
    electronegativity: 1.36,
    atomicRadius: 144,
    ionRadius: "74.5 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 633,
    electronAffinity: -18,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1814,
    boilingPoint: 3103,
    density: 2.985,
    groupBlock: "transition metal",
    yearDiscovered: 1879,
    electronsPerShell: [2, 8, 9, 2],
  },
  {
    element: "Ti",
    name: "Titanium",
    atomicNumber: 22,
    atomicMass: 47.867,
    group: 4,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Ti",
    electronConfig: "[Ar] 3d2 4s2",
    electronegativity: 1.54,
    atomicRadius: 136,
    ionRadius: "86 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 659,
    electronAffinity: -8,
    oxidationStates: "-1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1941,
    boilingPoint: 3560,
    density: 4.507,
    groupBlock: "transition metal",
    yearDiscovered: 1791,
    electronsPerShell: [2, 8, 10, 2],
  },
  {
    element: "V",
    name: "Vanadium",
    atomicNumber: 23,
    atomicMass: 50.9415,
    group: 5,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "V",
    electronConfig: "[Ar] 3d3 4s2",
    electronegativity: 1.63,
    atomicRadius: 125,
    ionRadius: "79 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 651,
    electronAffinity: -51,
    oxidationStates: "-1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2183,
    boilingPoint: 3680,
    density: 6.11,
    groupBlock: "transition metal",
    yearDiscovered: 1803,
    electronsPerShell: [2, 8, 11, 2],
  },
  {
    element: "Cr",
    name: "Chromium",
    atomicNumber: 24,
    atomicMass: 51.9961,
    group: 6,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Cr",
    electronConfig: "[Ar] 3d5 4s1",
    electronegativity: 1.66,
    atomicRadius: 127,
    ionRadius: "80 (+2*)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 653,
    electronAffinity: -64,
    oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2180,
    boilingPoint: 2944,
    density: 7.14,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 13, 1],
  },
  {
    element: "Mn",
    name: "Manganese",
    atomicNumber: 25,
    atomicMass: 54.938044,
    group: 7,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Mn",
    electronConfig: "[Ar] 3d5 4s2",
    electronegativity: 1.55,
    atomicRadius: 139,
    ionRadius: "67 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 717,
    electronAffinity: 0,
    oxidationStates: "-3, -2, -1, 1, 2, 3, 4, 5, 6, 7",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1519,
    boilingPoint: 2334,
    density: 7.47,
    groupBlock: "transition metal",
    yearDiscovered: 1774,
    electronsPerShell: [2, 8, 13, 2],
  },
  {
    element: "Fe",
    name: "Iron",
    atomicNumber: 26,
    atomicMass: 55.845,
    group: 8,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Fe",
    electronConfig: "[Ar] 3d6 4s2",
    electronegativity: 1.83,
    atomicRadius: 125,
    ionRadius: "78 (+2*)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 763,
    electronAffinity: -16,
    oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1811,
    boilingPoint: 3134,
    density: 7.874,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 14, 2],
  },
  {
    element: "Co",
    name: "Cobalt",
    atomicNumber: 27,
    atomicMass: 58.933194,
    group: 9,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Co",
    electronConfig: "[Ar] 3d7 4s2",
    electronegativity: 1.88,
    atomicRadius: 126,
    ionRadius: "74.5 (+2*)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 760,
    electronAffinity: -64,
    oxidationStates: "-1, 1, 2, 3, 4, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1768,
    boilingPoint: 3200,
    density: 8.9,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 15, 2],
  },
  {
    element: "Ni",
    name: "Nickel",
    atomicNumber: 28,
    atomicMass: 58.6934,
    group: 10,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Ni",
    electronConfig: "[Ar] 3d8 4s2",
    electronegativity: 1.91,
    atomicRadius: 121,
    ionRadius: "69 (+2)",
    vanDelWaalsRadius: 163,
    ionizationEnergy: 737,
    electronAffinity: -112,
    oxidationStates: "-1, 1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1728,
    boilingPoint: 3186,
    density: 8.908,
    groupBlock: "transition metal",
    yearDiscovered: 1751,
    electronsPerShell: [2, 8, 16, 2],
  },
  {
    element: "Cu",
    name: "Copper",
    atomicNumber: 29,
    atomicMass: 63.546,
    group: 11,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Cu",
    electronConfig: "[Ar] 3d10 4s1",
    electronegativity: 1.9,
    atomicRadius: 138,
    ionRadius: "77 (+1)",
    vanDelWaalsRadius: 140,
    ionizationEnergy: 746,
    electronAffinity: -118,
    oxidationStates: "1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1358,
    boilingPoint: 3200,
    density: 8.92,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 1],
  },
  {
    element: "Zn",
    name: "Zinc",
    atomicNumber: 30,
    atomicMass: 65.38,
    group: 12,
    period: 4,
    block: "d",
    state: "solid",
    symbol: "Zn",
    electronConfig: "[Ar] 3d10 4s2",
    electronegativity: 1.65,
    atomicRadius: 131,
    ionRadius: "74 (+2)",
    vanDelWaalsRadius: 139,
    ionizationEnergy: 906,
    electronAffinity: 0,
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 693,
    boilingPoint: 1180,
    density: 7.14,
    groupBlock: "transition metal",
    yearDiscovered: 1746,
    electronsPerShell: [2, 8, 18, 2],
  },
  {
    element: "Ga",
    name: "Gallium",
    atomicNumber: 31,
    atomicMass: 69.723,
    group: 13,
    period: 4,
    block: "p",
    state: "solid",
    symbol: "Ga",
    electronConfig: "[Ar] 3d10 4s2 4p1",
    electronegativity: 1.81,
    atomicRadius: 126,
    ionRadius: "62 (+3)",
    vanDelWaalsRadius: 187,
    ionizationEnergy: 579,
    electronAffinity: -29,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 303,
    boilingPoint: 2477,
    density: 5.904,
    groupBlock: "metal",
    yearDiscovered: 1875,
    electronsPerShell: [2, 8, 18, 3],
  },
  {
    element: "Ge",
    name: "Germanium",
    atomicNumber: 32,
    atomicMass: 72.63,
    group: 14,
    period: 4,
    block: "p",
    state: "solid",
    symbol: "Ge",
    electronConfig: "[Ar] 3d10 4s2 4p2",
    electronegativity: 2.01,
    atomicRadius: 122,
    ionRadius: "73 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 762,
    electronAffinity: -119,
    oxidationStates: "-4, 1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1211,
    boilingPoint: 3093,
    density: 5.323,
    groupBlock: "metalloid",
    yearDiscovered: 1886,
    electronsPerShell: [2, 8, 18, 4],
  },
  {
    element: "As",
    name: "Arsenic",
    atomicNumber: 33,
    atomicMass: 74.921595,
    group: 15,
    period: 4,
    block: "p",
    state: "solid",
    symbol: "As",
    electronConfig: "[Ar] 3d10 4s2 4p3",
    electronegativity: 2.18,
    atomicRadius: 119,
    ionRadius: "58 (+3)",
    vanDelWaalsRadius: 185,
    ionizationEnergy: 947,
    electronAffinity: -78,
    oxidationStates: "-3, 2, 3, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1090,
    boilingPoint: 887,
    density: 5.727,
    groupBlock: "metalloid",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 5],
  },
  {
    element: "Se",
    name: "Selenium",
    atomicNumber: 34,
    atomicMass: 78.971,
    group: 16,
    period: 4,
    block: "p",
    state: "solid",
    symbol: "Se",
    electronConfig: "[Ar] 3d10 4s2 4p4",
    electronegativity: 2.55,
    atomicRadius: 116,
    ionRadius: "198 (-2)",
    vanDelWaalsRadius: 190,
    ionizationEnergy: 941,
    electronAffinity: -195,
    oxidationStates: "-2, 2, 4, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 494,
    boilingPoint: 958,
    density: 4.819,
    groupBlock: "nonmetal",
    yearDiscovered: 1817,
    electronsPerShell: [2, 8, 18, 6],
  },
  {
    element: "Br",
    name: "Bromine",
    atomicNumber: 35,
    atomicMass: 79.904,
    group: 17,
    period: 4,
    block: "p",
    state: "liquid",
    symbol: "Br",
    electronConfig: "[Ar] 3d10 4s2 4p5",
    electronegativity: 2.96,
    atomicRadius: 114,
    ionRadius: "196 (-1)",
    vanDelWaalsRadius: 185,
    ionizationEnergy: 1140,
    electronAffinity: -325,
    oxidationStates: "-1, 1, 3, 4, 5, 7",
    standardState: "liquid",
    bondingType: "covalent network",
    meltingPoint: 266,
    boilingPoint: 332,
    density: 3.12,
    groupBlock: "halogen",
    yearDiscovered: 1826,
    electronsPerShell: [2, 8, 18, 7],
  },
  {
    element: "Kr",
    name: "Krypton",
    atomicNumber: 36,
    atomicMass: 83.798,
    group: 18,
    period: 4,
    block: "p",
    state: "gas",
    symbol: "Kr",
    electronConfig: "[Ar] 3d10 4s2 4p6",
    electronegativity: "",
    atomicRadius: 110,
    ionRadius: "",
    vanDelWaalsRadius: 202,
    ionizationEnergy: 1351,
    electronAffinity: 0,
    oxidationStates: "",
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: 116,
    boilingPoint: 120,
    density: 0.00375,
    groupBlock: "noble gas",
    yearDiscovered: 1898,
    electronsPerShell: [2, 8, 18, 8],
  },
  {
    element: "Rb",
    name: "Rubidium",
    atomicNumber: 37,
    atomicMass: 85.4678,
    group: 1,
    period: 5,
    block: "s",
    state: "solid",
    symbol: "Rb",
    electronConfig: "[Kr] 5s1",
    electronegativity: 0.82,
    atomicRadius: 211,
    ionRadius: "152 (+1)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 403,
    electronAffinity: -47,
    oxidationStates: 1,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 312,
    boilingPoint: 961,
    density: 1.532,
    groupBlock: "alkali metal",
    yearDiscovered: 1861,
    electronsPerShell: [2, 8, 18, 8, 1],
  },
  {
    element: "Sr",
    name: "Strontium",
    atomicNumber: 38,
    atomicMass: 87.62,
    group: 2,
    period: 5,
    block: "s",
    state: "solid",
    symbol: "Sr",
    electronConfig: "[Kr] 5s2",
    electronegativity: 0.95,
    atomicRadius: 192,
    ionRadius: "118 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 550,
    electronAffinity: -5,
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1050,
    boilingPoint: 1655,
    density: 2.63,
    groupBlock: "alkaline earth metal",
    yearDiscovered: 1790,
    electronsPerShell: [2, 8, 18, 8, 2],
  },
  {
    element: "Y",
    name: "Yttrium",
    atomicNumber: 39,
    atomicMass: 88.90584,
    group: 3,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Y",
    electronConfig: "[Kr] 4d1 5s2",
    electronegativity: 1.22,
    atomicRadius: 162,
    ionRadius: "90 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 600,
    electronAffinity: -30,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1799,
    boilingPoint: 3618,
    density: 4.472,
    groupBlock: "transition metal",
    yearDiscovered: 1794,
    electronsPerShell: [2, 8, 18, 9, 2],
  },
  {
    element: "Zr",
    name: "Zirconium",
    atomicNumber: 40,
    atomicMass: 91.224,
    group: 4,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Zr",
    electronConfig: "[Kr] 4d2 5s2",
    electronegativity: 1.33,
    atomicRadius: 148,
    ionRadius: "72 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 640,
    electronAffinity: -41,
    oxidationStates: "1, 2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2128,
    boilingPoint: 4682,
    density: 6.511,
    groupBlock: "transition metal",
    yearDiscovered: 1789,
    electronsPerShell: [2, 8, 18, 10, 2],
  },
  {
    element: "Nb",
    name: "Niobium",
    atomicNumber: 41,
    atomicMass: 92.90637,
    group: 5,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Nb",
    electronConfig: "[Kr] 4d4 5s1",
    electronegativity: 1.6,
    atomicRadius: 137,
    ionRadius: "72 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 652,
    electronAffinity: -86,
    oxidationStates: "-1, 2, 3, 4, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2750,
    boilingPoint: 5017,
    density: 8.57,
    groupBlock: "transition metal",
    yearDiscovered: 1801,
    electronsPerShell: [2, 8, 18, 12, 1],
  },
  {
    element: "Mo",
    name: "Molybdenum",
    atomicNumber: 42,
    atomicMass: 95.95,
    group: 6,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Mo",
    electronConfig: "[Kr] 4d5 5s1",
    electronegativity: 2.16,
    atomicRadius: 145,
    ionRadius: "69 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 684,
    electronAffinity: -72,
    oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2896,
    boilingPoint: 4912,
    density: 10.28,
    groupBlock: "transition metal",
    yearDiscovered: 1778,
    electronsPerShell: [2, 8, 18, 13, 1],
  },
  {
    element: "Tc",
    name: "Technetium",
    atomicNumber: 43,
    atomicMass: 98,
    group: 7,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Tc",
    electronConfig: "[Kr] 4d5 5s2",
    electronegativity: 1.9,
    atomicRadius: 156,
    ionRadius: "64.5 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 702,
    electronAffinity: -53,
    oxidationStates: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2430,
    boilingPoint: 4538,
    density: 11.5,
    groupBlock: "transition metal",
    yearDiscovered: 1937,
    electronsPerShell: [2, 8, 18, 13, 2],
  },
  {
    element: "Ru",
    name: "Ruthenium",
    atomicNumber: 44,
    atomicMass: 101.07,
    group: 8,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Ru",
    electronConfig: "[Kr] 4d7 5s1",
    electronegativity: 2.2,
    atomicRadius: 126,
    ionRadius: "68 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 710,
    electronAffinity: -101,
    oxidationStates: "-2, 1, 2, 3, 4, 5, 6, 7, 8",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2607,
    boilingPoint: 4423,
    density: 12.37,
    groupBlock: "transition metal",
    yearDiscovered: 1844,
    electronsPerShell: [2, 8, 18, 15, 1],
  },
  {
    element: "Rh",
    name: "Rhodium",
    atomicNumber: 45,
    atomicMass: 102.9055,
    group: 9,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Rh",
    electronConfig: "[Kr] 4d8 5s1",
    electronegativity: 2.28,
    atomicRadius: 135,
    ionRadius: "66.5 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 720,
    electronAffinity: -110,
    oxidationStates: "-1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2237,
    boilingPoint: 3968,
    density: 12.45,
    groupBlock: "transition metal",
    yearDiscovered: 1803,
    electronsPerShell: [2, 8, 18, 16, 1],
  },
  {
    element: "Pd",
    name: "Palladium",
    atomicNumber: 46,
    atomicMass: 106.42,
    group: 10,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Pd",
    electronConfig: "[Kr] 4d10",
    electronegativity: 2.2,
    atomicRadius: 131,
    ionRadius: "59 (+1)",
    vanDelWaalsRadius: 163,
    ionizationEnergy: 804,
    electronAffinity: -54,
    oxidationStates: "2, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1828,
    boilingPoint: 3236,
    density: 12.02,
    groupBlock: "transition metal",
    yearDiscovered: 1803,
    electronsPerShell: [2, 8, 18, 18],
  },
  {
    element: "Ag",
    name: "Silver",
    atomicNumber: 47,
    atomicMass: 107.8682,
    group: 11,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Ag",
    electronConfig: "[Kr] 4d10 5s1",
    electronegativity: 1.93,
    atomicRadius: 153,
    ionRadius: "115 (+1)",
    vanDelWaalsRadius: 172,
    ionizationEnergy: 731,
    electronAffinity: -126,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1235,
    boilingPoint: 2435,
    density: 10.501,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 18, 1],
  },
  {
    element: "Cd",
    name: "Cadmium",
    atomicNumber: 48,
    atomicMass: 112.414,
    group: 12,
    period: 5,
    block: "d",
    state: "solid",
    symbol: "Cd",
    electronConfig: "[Kr] 4d10 5s2",
    electronegativity: 1.69,
    atomicRadius: 148,
    ionRadius: "95 (+2)",
    vanDelWaalsRadius: 158,
    ionizationEnergy: 868,
    electronAffinity: 0,
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 594,
    boilingPoint: 1040,
    density: 8.69,
    groupBlock: "transition metal",
    yearDiscovered: 1817,
    electronsPerShell: [2, 8, 18, 18, 2],
  },
  {
    element: "In",
    name: "Indium",
    atomicNumber: 49,
    atomicMass: 114.818,
    group: 13,
    period: 5,
    block: "p",
    state: "solid",
    symbol: "In",
    electronConfig: "[Kr] 4d10 5s2 5p1",
    electronegativity: 1.78,
    atomicRadius: 144,
    ionRadius: "80 (+3)",
    vanDelWaalsRadius: 193,
    ionizationEnergy: 558,
    electronAffinity: -29,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 430,
    boilingPoint: 2345,
    density: 7.31,
    groupBlock: "metal",
    yearDiscovered: 1863,
    electronsPerShell: [2, 8, 18, 18, 3],
  },
  {
    element: "Sn",
    name: "Tin",
    atomicNumber: 50,
    atomicMass: 118.71,
    group: 14,
    period: 5,
    block: "p",
    state: "solid",
    symbol: "Sn",
    electronConfig: "[Kr] 4d10 5s2 5p2",
    electronegativity: 1.96,
    atomicRadius: 141,
    ionRadius: "112 (+2)",
    vanDelWaalsRadius: 217,
    ionizationEnergy: 709,
    electronAffinity: -107,
    oxidationStates: "-4, 2, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 505,
    boilingPoint: 2875,
    density: 7.287,
    groupBlock: "metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 18, 4],
  },
  {
    element: "Sb",
    name: "Antimony",
    atomicNumber: 51,
    atomicMass: 121.76,
    group: 15,
    period: 5,
    block: "p",
    state: "solid",
    symbol: "Sb",
    electronConfig: "[Kr] 4d10 5s2 5p3",
    electronegativity: 2.05,
    atomicRadius: 138,
    ionRadius: "76 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 834,
    electronAffinity: -103,
    oxidationStates: "-3, 3, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 904,
    boilingPoint: 1860,
    density: 6.685,
    groupBlock: "metalloid",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 18, 5],
  },
  {
    element: "Te",
    name: "Tellurium",
    atomicNumber: 52,
    atomicMass: 127.6,
    group: 16,
    period: 5,
    block: "p",
    state: "solid",
    symbol: "Te",
    electronConfig: "[Kr] 4d10 5s2 5p4",
    electronegativity: 2.1,
    atomicRadius: 135,
    ionRadius: "221 (-2)",
    vanDelWaalsRadius: 206,
    ionizationEnergy: 869,
    electronAffinity: -190,
    oxidationStates: "-2, 2, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 723,
    boilingPoint: 1261,
    density: 6.232,
    groupBlock: "metalloid",
    yearDiscovered: 1782,
    electronsPerShell: [2, 8, 18, 18, 6],
  },
  {
    element: "I",
    name: "Iodine",
    atomicNumber: 53,
    atomicMass: 126.90447,
    group: 17,
    period: 5,
    block: "p",
    state: "solid",
    symbol: "I",
    electronConfig: "[Kr] 4d10 5s2 5p5",
    electronegativity: 2.66,
    atomicRadius: 133,
    ionRadius: "220 (-1)",
    vanDelWaalsRadius: 198,
    ionizationEnergy: 1008,
    electronAffinity: -295,
    oxidationStates: "-1, 1, 3, 5, 7",
    standardState: "solid",
    bondingType: "covalent network",
    meltingPoint: 387,
    boilingPoint: 457,
    density: 4.94,
    groupBlock: "halogen",
    yearDiscovered: 1811,
    electronsPerShell: [2, 8, 18, 18, 7],
  },
  {
    element: "Xe",
    name: "Xenon",
    atomicNumber: 54,
    atomicMass: 131.293,
    group: 18,
    period: 5,
    block: "p",
    state: "gas",
    symbol: "Xe",
    electronConfig: "[Kr] 4d10 5s2 5p6",
    electronegativity: "",
    atomicRadius: 130,
    ionRadius: "48 (+8)",
    vanDelWaalsRadius: 216,
    ionizationEnergy: 1170,
    electronAffinity: 0,
    oxidationStates: "2, 4, 6, 8",
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: 161,
    boilingPoint: 165,
    density: 0.0059,
    groupBlock: "noble gas",
    yearDiscovered: 1898,
    electronsPerShell: [2, 8, 18, 18, 8],
  },
  {
    element: "Cs",
    name: "Cesium",
    atomicNumber: 55,
    atomicMass: 132.90545196,
    group: 1,
    period: 6,
    block: "s",
    state: "solid",
    symbol: "Cs",
    electronConfig: "[Xe] 6s1",
    electronegativity: 0.79,
    atomicRadius: 225,
    ionRadius: "167 (+1)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 376,
    electronAffinity: -46,
    oxidationStates: 1,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 302,
    boilingPoint: 944,
    density: 1.879,
    groupBlock: "alkali metal",
    yearDiscovered: 1860,
    electronsPerShell: [2, 8, 18, 18, 8, 1],
  },
  {
    element: "Ba",
    name: "Barium",
    atomicNumber: 56,
    atomicMass: 137.327,
    group: 2,
    period: 6,
    block: "s",
    state: "solid",
    symbol: "Ba",
    electronConfig: "[Xe] 6s2",
    electronegativity: 0.89,
    atomicRadius: 198,
    ionRadius: "135 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 503,
    electronAffinity: -14,
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1000,
    boilingPoint: 2143,
    density: 3.51,
    groupBlock: "alkaline earth metal",
    yearDiscovered: 1808,
    electronsPerShell: [2, 8, 18, 18, 8, 2],
  },
  {
    element: "La",
    name: "Lanthanum",
    atomicNumber: 57,
    atomicMass: 138.90547,
    group: "",
    period: 6,
    block: "d",
    state: "solid",
    symbol: "La",
    electronConfig: "[Xe] 5d1 6s2",
    electronegativity: 1.1,
    atomicRadius: 169,
    ionRadius: "103.2 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 538,
    electronAffinity: -48,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1193,
    boilingPoint: 3737,
    density: 6.146,
    groupBlock: "lanthanoid",
    yearDiscovered: 1839,
    electronsPerShell: [2, 8, 18, 18, 9, 2],
  },
  {
    element: "Ce",
    name: "Cerium",
    atomicNumber: 58,
    atomicMass: 140.116,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Ce",
    electronConfig: "[Xe] 4f1 5d1 6s2",
    electronegativity: 1.12,
    atomicRadius: "",
    ionRadius: "102 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 534,
    electronAffinity: -50,
    oxidationStates: "2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1071,
    boilingPoint: 3633,
    density: 6.689,
    groupBlock: "lanthanoid",
    yearDiscovered: 1803,
    electronsPerShell: [2, 8, 18, 19, 9, 2],
  },
  {
    element: "Pr",
    name: "Praseodymium",
    atomicNumber: 59,
    atomicMass: 140.90766,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Pr",
    electronConfig: "[Xe] 4f3 6s2",
    electronegativity: 1.13,
    atomicRadius: "",
    ionRadius: "99 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 527,
    electronAffinity: -50,
    oxidationStates: "2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1204,
    boilingPoint: 3563,
    density: 6.64,
    groupBlock: "lanthanoid",
    yearDiscovered: 1885,
    electronsPerShell: [2, 8, 18, 21, 8, 2],
  },
  {
    element: "Nd",
    name: "Neodymium",
    atomicNumber: 60,
    atomicMass: 144.242,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Nd",
    electronConfig: "[Xe] 4f4 6s2",
    electronegativity: 1.14,
    atomicRadius: "",
    ionRadius: "129 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 533,
    electronAffinity: -50,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1294,
    boilingPoint: 3373,
    density: 7.01,
    groupBlock: "lanthanoid",
    yearDiscovered: 1885,
    electronsPerShell: [2, 8, 18, 22, 8, 2],
  },
  {
    element: "Pm",
    name: "Promethium",
    atomicNumber: 61,
    atomicMass: 145,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Pm",
    electronConfig: "[Xe] 4f5 6s2",
    electronegativity: 1.13,
    atomicRadius: "",
    ionRadius: "97 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 540,
    electronAffinity: -50,
    oxidationStates: 3,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1373,
    boilingPoint: 3273,
    density: 7.264,
    groupBlock: "lanthanoid",
    yearDiscovered: 1947,
    electronsPerShell: [2, 8, 18, 23, 8, 2],
  },
  {
    element: "Sm",
    name: "Samarium",
    atomicNumber: 62,
    atomicMass: 150.36,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Sm",
    electronConfig: "[Xe] 4f6 6s2",
    electronegativity: 1.17,
    atomicRadius: "",
    ionRadius: "122 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 545,
    electronAffinity: -50,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1345,
    boilingPoint: 2076,
    density: 7.353,
    groupBlock: "lanthanoid",
    yearDiscovered: 1879,
    electronsPerShell: [2, 8, 18, 24, 8, 2],
  },
  {
    element: "Eu",
    name: "Europium",
    atomicNumber: 63,
    atomicMass: 151.964,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Eu",
    electronConfig: "[Xe] 4f7 6s2",
    electronegativity: 1.2,
    atomicRadius: "",
    ionRadius: "117 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 547,
    electronAffinity: -50,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1095,
    boilingPoint: 1800,
    density: 5.244,
    groupBlock: "lanthanoid",
    yearDiscovered: 1901,
    electronsPerShell: [2, 8, 18, 25, 8, 2],
  },
  {
    element: "Gd",
    name: "Gadolinium",
    atomicNumber: 64,
    atomicMass: 157.25,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Gd",
    electronConfig: "[Xe] 4f7 5d1 6s2",
    electronegativity: 1.2,
    atomicRadius: "",
    ionRadius: "93.8 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 593,
    electronAffinity: -50,
    oxidationStates: "1, 2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1586,
    boilingPoint: 3523,
    density: 7.901,
    groupBlock: "lanthanoid",
    yearDiscovered: 1880,
    electronsPerShell: [2, 8, 18, 25, 9, 2],
  },
  {
    element: "Tb",
    name: "Terbium",
    atomicNumber: 65,
    atomicMass: 158.92535,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Tb",
    electronConfig: "[Xe] 4f9 6s2",
    electronegativity: 1.2,
    atomicRadius: "",
    ionRadius: "92.3 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 566,
    electronAffinity: -50,
    oxidationStates: "1, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1629,
    boilingPoint: 3503,
    density: 8.219,
    groupBlock: "lanthanoid",
    yearDiscovered: 1843,
    electronsPerShell: [2, 8, 18, 27, 8, 2],
  },
  {
    element: "Dy",
    name: "Dysprosium",
    atomicNumber: 66,
    atomicMass: 162.5,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Dy",
    electronConfig: "[Xe] 4f10 6s2",
    electronegativity: 1.22,
    atomicRadius: "",
    ionRadius: "107 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 573,
    electronAffinity: -50,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1685,
    boilingPoint: 2840,
    density: 8.551,
    groupBlock: "lanthanoid",
    yearDiscovered: 1886,
    electronsPerShell: [2, 8, 18, 28, 8, 2],
  },
  {
    element: "Ho",
    name: "Holmium",
    atomicNumber: 67,
    atomicMass: 164.93033,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Ho",
    electronConfig: "[Xe] 4f11 6s2",
    electronegativity: 1.23,
    atomicRadius: "",
    ionRadius: "90.1 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 581,
    electronAffinity: -50,
    oxidationStates: 3,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1747,
    boilingPoint: 2973,
    density: 8.795,
    groupBlock: "lanthanoid",
    yearDiscovered: 1878,
    electronsPerShell: [2, 8, 18, 29, 8, 2],
  },
  {
    element: "Er",
    name: "Erbium",
    atomicNumber: 68,
    atomicMass: 167.259,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Er",
    electronConfig: "[Xe] 4f12 6s2",
    electronegativity: 1.24,
    atomicRadius: "",
    ionRadius: "89 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 589,
    electronAffinity: -50,
    oxidationStates: "1, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1770,
    boilingPoint: 3141,
    density: 9.066,
    groupBlock: "lanthanoid",
    yearDiscovered: 1842,
    electronsPerShell: [2, 8, 18, 30, 8, 2],
  },
  {
    element: "Tm",
    name: "Thulium",
    atomicNumber: 69,
    atomicMass: 168.93422,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Tm",
    electronConfig: "[Xe] 4f13 6s2",
    electronegativity: 1.25,
    atomicRadius: "",
    ionRadius: "103 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 597,
    electronAffinity: -50,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1818,
    boilingPoint: 2223,
    density: 9.321,
    groupBlock: "lanthanoid",
    yearDiscovered: 1879,
    electronsPerShell: [2, 8, 18, 31, 8, 2],
  },
  {
    element: "Yb",
    name: "Ytterbium",
    atomicNumber: 70,
    atomicMass: 173.045,
    group: "",
    period: 6,
    block: "f",
    state: "solid",
    symbol: "Yb",
    electronConfig: "[Xe] 4f14 6s2",
    electronegativity: 1.1,
    atomicRadius: "",
    ionRadius: "102 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 603,
    electronAffinity: -50,
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1092,
    boilingPoint: 1469,
    density: 6.57,
    groupBlock: "lanthanoid",
    yearDiscovered: 1878,
    electronsPerShell: [2, 8, 18, 32, 8, 2],
  },
  {
    element: "Lu",
    name: "Lutetium",
    atomicNumber: 71,
    atomicMass: 174.9668,
    group: "",
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Lu",
    electronConfig: "[Xe] 4f14 5d1 6s2",
    electronegativity: 1.27,
    atomicRadius: 160,
    ionRadius: "86.1 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 524,
    electronAffinity: -50,
    oxidationStates: 3,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1936,
    boilingPoint: 3675,
    density: 9.841,
    groupBlock: "lanthanoid",
    yearDiscovered: 1907,
    electronsPerShell: [2, 8, 18, 32, 9, 2],
  },
  {
    element: "Hf",
    name: "Hafnium",
    atomicNumber: 72,
    atomicMass: 178.49,
    group: 4,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Hf",
    electronConfig: "[Xe] 4f14 5d2 6s2",
    electronegativity: 1.3,
    atomicRadius: 150,
    ionRadius: "71 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 659,
    electronAffinity: 0,
    oxidationStates: "2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2506,
    boilingPoint: 4876,
    density: 13.31,
    groupBlock: "transition metal",
    yearDiscovered: 1923,
    electronsPerShell: [2, 8, 18, 32, 10, 2],
  },
  {
    element: "Ta",
    name: "Tantalum",
    atomicNumber: 73,
    atomicMass: 180.94788,
    group: 5,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Ta",
    electronConfig: "[Xe] 4f14 5d3 6s2",
    electronegativity: 1.5,
    atomicRadius: 138,
    ionRadius: "72 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 761,
    electronAffinity: -31,
    oxidationStates: "-1, 2, 3, 4, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 3290,
    boilingPoint: 5731,
    density: 16.65,
    groupBlock: "transition metal",
    yearDiscovered: 1802,
    electronsPerShell: [2, 8, 18, 32, 11, 2],
  },
  {
    element: "W",
    name: "Tungsten",
    atomicNumber: 74,
    atomicMass: 183.84,
    group: 6,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "W",
    electronConfig: "[Xe] 4f14 5d4 6s2",
    electronegativity: 2.36,
    atomicRadius: 146,
    ionRadius: "66 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 770,
    electronAffinity: -79,
    oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 3695,
    boilingPoint: 5828,
    density: 19.25,
    groupBlock: "transition metal",
    yearDiscovered: 1783,
    electronsPerShell: [2, 8, 18, 32, 12, 2],
  },
  {
    element: "Re",
    name: "Rhenium",
    atomicNumber: 75,
    atomicMass: 186.207,
    group: 7,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Re",
    electronConfig: "[Xe] 4f14 5d5 6s2",
    electronegativity: 1.9,
    atomicRadius: 159,
    ionRadius: "63 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 760,
    electronAffinity: -15,
    oxidationStates: "-3, -1, 1, 2, 3, 4, 5, 6, 7",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 3459,
    boilingPoint: 5869,
    density: 21.02,
    groupBlock: "transition metal",
    yearDiscovered: 1925,
    electronsPerShell: [2, 8, 18, 32, 13, 2],
  },
  {
    element: "Os",
    name: "Osmium",
    atomicNumber: 76,
    atomicMass: 190.23,
    group: 8,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Os",
    electronConfig: "[Xe] 4f14 5d6 6s2",
    electronegativity: 2.2,
    atomicRadius: 128,
    ionRadius: "63 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 840,
    electronAffinity: -106,
    oxidationStates: "-2, -1, 1, 2, 3, 4, 5, 6, 7, 8",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 3306,
    boilingPoint: 5285,
    density: 22.61,
    groupBlock: "transition metal",
    yearDiscovered: 1803,
    electronsPerShell: [2, 8, 18, 32, 14, 2],
  },
  {
    element: "Ir",
    name: "Iridium",
    atomicNumber: 77,
    atomicMass: 192.217,
    group: 9,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Ir",
    electronConfig: "[Xe] 4f14 5d7 6s2",
    electronegativity: 2.2,
    atomicRadius: 137,
    ionRadius: "68 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 880,
    electronAffinity: -151,
    oxidationStates: "-3, -1, 1, 2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2739,
    boilingPoint: 4701,
    density: 22.65,
    groupBlock: "transition metal",
    yearDiscovered: 1803,
    electronsPerShell: [2, 8, 18, 32, 15, 2],
  },
  {
    element: "Pt",
    name: "Platinum",
    atomicNumber: 78,
    atomicMass: 195.084,
    group: 10,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Pt",
    electronConfig: "[Xe] 4f14 5d9 6s1",
    electronegativity: 2.28,
    atomicRadius: 128,
    ionRadius: "86 (+2)",
    vanDelWaalsRadius: 175,
    ionizationEnergy: 870,
    electronAffinity: -205,
    oxidationStates: "2, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2041,
    boilingPoint: 4098,
    density: 21.09,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 32, 17, 1],
  },
  {
    element: "Au",
    name: "Gold",
    atomicNumber: 79,
    atomicMass: 196.966569,
    group: 11,
    period: 6,
    block: "d",
    state: "solid",
    symbol: "Au",
    electronConfig: "[Xe] 4f14 5d10 6s1",
    electronegativity: 2.54,
    atomicRadius: 144,
    ionRadius: "137 (+1)",
    vanDelWaalsRadius: 166,
    ionizationEnergy: 890,
    electronAffinity: -223,
    oxidationStates: "-1, 1, 2, 3, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1337,
    boilingPoint: 3129,
    density: 19.3,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 32, 18, 1],
  },
  {
    element: "Hg",
    name: "Mercury",
    atomicNumber: 80,
    atomicMass: 200.592,
    group: 12,
    period: 6,
    block: "d",
    state: "liquid",
    symbol: "Hg",
    electronConfig: "[Xe] 4f14 5d10 6s2",
    electronegativity: 2,
    atomicRadius: 149,
    ionRadius: "119 (+1)",
    vanDelWaalsRadius: 155,
    ionizationEnergy: 1007,
    electronAffinity: 0,
    oxidationStates: "1, 2, 4",
    standardState: "liquid",
    bondingType: "metallic",
    meltingPoint: 234,
    boilingPoint: 630,
    density: 13.534,
    groupBlock: "transition metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 32, 18, 2],
  },
  {
    element: "Tl",
    name: "Thallium",
    atomicNumber: 81,
    atomicMass: 204.38,
    group: 13,
    period: 6,
    block: "p",
    state: "solid",
    symbol: "Tl",
    electronConfig: "[Xe] 4f14 5d10 6s2 6p1",
    electronegativity: 2.04,
    atomicRadius: 148,
    ionRadius: "150 (+1)",
    vanDelWaalsRadius: 196,
    ionizationEnergy: 589,
    electronAffinity: -19,
    oxidationStates: "1, 3",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 577,
    boilingPoint: 1746,
    density: 11.85,
    groupBlock: "metal",
    yearDiscovered: 1861,
    electronsPerShell: [2, 8, 18, 32, 18, 3],
  },
  {
    element: "Pb",
    name: "Lead",
    atomicNumber: 82,
    atomicMass: 207.2,
    group: 14,
    period: 6,
    block: "p",
    state: "solid",
    symbol: "Pb",
    electronConfig: "[Xe] 4f14 5d10 6s2 6p2",
    electronegativity: 2.33,
    atomicRadius: 147,
    ionRadius: "119 (+2)",
    vanDelWaalsRadius: 202,
    ionizationEnergy: 716,
    electronAffinity: -35,
    oxidationStates: "-4, 2, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 601,
    boilingPoint: 2022,
    density: 11.34,
    groupBlock: "metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 32, 18, 4],
  },
  {
    element: "Bi",
    name: "Bismuth",
    atomicNumber: 83,
    atomicMass: 208.9804,
    group: 15,
    period: 6,
    block: "p",
    state: "solid",
    symbol: "Bi",
    electronConfig: "[Xe] 4f14 5d10 6s2 6p3",
    electronegativity: 2.02,
    atomicRadius: 146,
    ionRadius: "103 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 703,
    electronAffinity: -91,
    oxidationStates: "-3, 3, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 544,
    boilingPoint: 1837,
    density: 9.78,
    groupBlock: "metal",
    yearDiscovered: "Ancient",
    electronsPerShell: [2, 8, 18, 32, 18, 5],
  },
  {
    element: "Po",
    name: "Polonium",
    atomicNumber: 84,
    atomicMass: 209,
    group: 16,
    period: 6,
    block: "p",
    state: "solid",
    symbol: "Po",
    electronConfig: "[Xe] 4f14 5d10 6s2 6p4",
    electronegativity: 2,
    atomicRadius: "",
    ionRadius: "94 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 812,
    electronAffinity: -183,
    oxidationStates: "-2, 2, 4, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 527,
    boilingPoint: 1235,
    density: 9.196,
    groupBlock: "metalloid",
    yearDiscovered: 1898,
    electronsPerShell: [2, 8, 18, 32, 18, 6],
  },
  {
    element: "At",
    name: "Astatine",
    atomicNumber: 85,
    atomicMass: 210,
    group: 17,
    period: 6,
    block: "p",
    state: "solid",
    symbol: "At",
    electronConfig: "[Xe] 4f14 5d10 6s2 6p5",
    electronegativity: 2.2,
    atomicRadius: "",
    ionRadius: "62 (+7)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 920,
    electronAffinity: -270,
    oxidationStates: "-1, 1, 3, 5",
    standardState: "solid",
    bondingType: "covalent network",
    meltingPoint: 575,
    boilingPoint: "",
    density: "",
    groupBlock: "halogen",
    yearDiscovered: 1940,
    electronsPerShell: [2, 8, 18, 32, 18, 7],
  },
  {
    element: "Rn",
    name: "Radon",
    atomicNumber: 86,
    atomicMass: 222,
    group: 18,
    period: 6,
    block: "p",
    state: "gas",
    symbol: "Rn",
    electronConfig: "[Xe] 4f14 5d10 6s2 6p6",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: 220,
    ionizationEnergy: 1037,
    electronAffinity: "",
    oxidationStates: 2,
    standardState: "gas",
    bondingType: "atomic",
    meltingPoint: 202,
    boilingPoint: 211,
    density: 0.00973,
    groupBlock: "noble gas",
    yearDiscovered: 1900,
    electronsPerShell: [2, 8, 18, 32, 18, 8],
  },
  {
    element: "Fr",
    name: "Francium",
    atomicNumber: 87,
    atomicMass: 223,
    group: 1,
    period: 7,
    block: "s",
    state: "solid",
    symbol: "Fr",
    electronConfig: "[Rn] 7s1",
    electronegativity: 0.7,
    atomicRadius: "",
    ionRadius: "180 (+1)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 380,
    electronAffinity: "",
    oxidationStates: 1,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: "",
    boilingPoint: "",
    density: "",
    groupBlock: "alkali metal",
    yearDiscovered: 1939,
    electronsPerShell: [2, 8, 18, 32, 18, 8, 1],
  },
  {
    element: "Ra",
    name: "Radium",
    atomicNumber: 88,
    atomicMass: 226,
    group: 2,
    period: 7,
    block: "s",
    state: "solid",
    symbol: "Ra",
    electronConfig: "[Rn] 7s2",
    electronegativity: 0.9,
    atomicRadius: "",
    ionRadius: "148 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 509,
    electronAffinity: "",
    oxidationStates: 2,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 973,
    boilingPoint: 2010,
    density: 5,
    groupBlock: "alkaline earth metal",
    yearDiscovered: 1898,
    electronsPerShell: [2, 8, 18, 32, 18, 8, 2],
  },
  {
    element: "Ac",
    name: "Actinium",
    atomicNumber: 89,
    atomicMass: 227,
    group: "",
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Ac",
    electronConfig: "[Rn] 6d1 7s2",
    electronegativity: 1.1,
    atomicRadius: "",
    ionRadius: "112 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 499,
    electronAffinity: "",
    oxidationStates: 3,
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1323,
    boilingPoint: 3473,
    density: 10.07,
    groupBlock: "actinoid",
    yearDiscovered: 1899,
    electronsPerShell: [2, 8, 18, 32, 18, 9, 2],
  },
  {
    element: "Th",
    name: "Thorium",
    atomicNumber: 90,
    atomicMass: 232.0377,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Th",
    electronConfig: "[Rn] 6d2 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "94 (+4)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 587,
    electronAffinity: "",
    oxidationStates: "2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 2023,
    boilingPoint: 5093,
    density: 11.72,
    groupBlock: "actinoid",
    yearDiscovered: 1828,
    electronsPerShell: [2, 8, 18, 32, 18, 10, 2],
  },
  {
    element: "Pa",
    name: "Protactinium",
    atomicNumber: 91,
    atomicMass: 231.03588,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Pa",
    electronConfig: "[Rn] 5f2 6d1 7s2",
    electronegativity: 1.5,
    atomicRadius: "",
    ionRadius: "104 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 568,
    electronAffinity: "",
    oxidationStates: "3, 4, 5",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1845,
    boilingPoint: 4273,
    density: 15.37,
    groupBlock: "actinoid",
    yearDiscovered: 1913,
    electronsPerShell: [2, 8, 18, 32, 20, 9, 2],
  },
  {
    element: "U",
    name: "Uranium",
    atomicNumber: 92,
    atomicMass: 238.02891,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "U",
    electronConfig: "[Rn] 5f3 6d1 7s2",
    electronegativity: 1.38,
    atomicRadius: "",
    ionRadius: "102.5 (+3)",
    vanDelWaalsRadius: 186,
    ionizationEnergy: 598,
    electronAffinity: "",
    oxidationStates: "3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1408,
    boilingPoint: 4200,
    density: 19.05,
    groupBlock: "actinoid",
    yearDiscovered: 1789,
    electronsPerShell: [2, 8, 18, 32, 21, 9, 2],
  },
  {
    element: "Np",
    name: "Neptunium",
    atomicNumber: 93,
    atomicMass: 237,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Np",
    electronConfig: "[Rn] 5f4 6d1 7s2",
    electronegativity: 1.36,
    atomicRadius: "",
    ionRadius: "110 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 605,
    electronAffinity: "",
    oxidationStates: "3, 4, 5, 6, 7",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 917,
    boilingPoint: 4273,
    density: 20.45,
    groupBlock: "actinoid",
    yearDiscovered: 1940,
    electronsPerShell: [2, 8, 18, 32, 22, 9, 2],
  },
  {
    element: "Pu",
    name: "Plutonium",
    atomicNumber: 94,
    atomicMass: 244,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Pu",
    electronConfig: "[Rn] 5f6 7s2",
    electronegativity: 1.28,
    atomicRadius: "",
    ionRadius: "100 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 585,
    electronAffinity: "",
    oxidationStates: "3, 4, 5, 6, 7",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 913,
    boilingPoint: 3503,
    density: 19.84,
    groupBlock: "actinoid",
    yearDiscovered: 1940,
    electronsPerShell: [2, 8, 18, 32, 24, 8, 2],
  },
  {
    element: "Am",
    name: "Americium",
    atomicNumber: 95,
    atomicMass: 243,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Am",
    electronConfig: "[Rn] 5f7 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "126 (+2)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 578,
    electronAffinity: "",
    oxidationStates: "2, 3, 4, 5, 6",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1449,
    boilingPoint: 2284,
    density: 13.69,
    groupBlock: "actinoid",
    yearDiscovered: 1944,
    electronsPerShell: [2, 8, 18, 32, 25, 8, 2],
  },
  {
    element: "Cm",
    name: "Curium",
    atomicNumber: 96,
    atomicMass: 247,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Cm",
    electronConfig: "[Rn] 5f7 6d1 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "97 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 581,
    electronAffinity: "",
    oxidationStates: "3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1618,
    boilingPoint: 3383,
    density: 13.51,
    groupBlock: "actinoid",
    yearDiscovered: 1944,
    electronsPerShell: [2, 8, 18, 32, 25, 9, 2],
  },
  {
    element: "Bk",
    name: "Berkelium",
    atomicNumber: 97,
    atomicMass: 247,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Bk",
    electronConfig: "[Rn] 5f9 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "96 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 601,
    electronAffinity: "",
    oxidationStates: "3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1323,
    boilingPoint: "",
    density: 14.78,
    groupBlock: "actinoid",
    yearDiscovered: 1949,
    electronsPerShell: [2, 8, 18, 32, 27, 8, 2],
  },
  {
    element: "Cf",
    name: "Californium",
    atomicNumber: 98,
    atomicMass: 251,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Cf",
    electronConfig: "[Rn] 5f10 7s2",
    electronegativity: 1.3,
    atomicRadius: "",

    ionRadius: "95 (+3)",
    vanDelWaalsRadius: "",
    ionizationEnergy: 608,
    electronAffinity: "",
    oxidationStates: "2, 3, 4",
    standardState: "solid",
    bondingType: "metallic",
    meltingPoint: 1173,
    boilingPoint: "",
    density: 15.1,
    groupBlock: "actinoid",
    yearDiscovered: 1950,
    electronsPerShell: [2, 8, 18, 32, 28, 8, 2],
  },
  {
    element: "Es",
    name: "Einsteinium",
    atomicNumber: 99,
    atomicMass: 252,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Es",
    electronConfig: "[Rn] 5f11 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 619,
    electronAffinity: "",
    oxidationStates: "2, 3",
    standardState: "solid",
    bondingType: "",
    meltingPoint: 1133,
    boilingPoint: "",
    density: "",
    groupBlock: "actinoid",
    yearDiscovered: 1952,
    electronsPerShell: [2, 8, 18, 32, 29, 8, 2],
  },
  {
    element: "Fm",
    name: "Fermium",
    atomicNumber: 100,
    atomicMass: 257,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Fm",
    electronConfig: "[Rn] 5f12 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 627,
    electronAffinity: "",
    oxidationStates: "2, 3",
    standardState: "",
    bondingType: "",
    meltingPoint: 1800,
    boilingPoint: "",
    density: "",
    groupBlock: "actinoid",
    yearDiscovered: 1952,
    electronsPerShell: [2, 8, 18, 32, 30, 8, 2],
  },
  {
    element: "Md",
    name: "Mendelevium",
    atomicNumber: 101,
    atomicMass: 258,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "Md",
    electronConfig: "[Rn] 5f13 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 635,
    electronAffinity: "",
    oxidationStates: "2, 3",
    standardState: "",
    bondingType: "",
    meltingPoint: 1100,
    boilingPoint: "",
    density: "",
    groupBlock: "actinoid",
    yearDiscovered: 1955,
    electronsPerShell: [2, 8, 18, 32, 31, 8, 2],
  },
  {
    element: "No",
    name: "Nobelium",
    atomicNumber: 102,
    atomicMass: 259,
    group: "",
    period: 7,
    block: "f",
    state: "solid",
    symbol: "No",
    electronConfig: "[Rn] 5f14 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 642,
    electronAffinity: "",
    oxidationStates: "2, 3",
    standardState: "",
    bondingType: "",
    meltingPoint: 1100,
    boilingPoint: "",
    density: "",
    groupBlock: "actinoid",
    yearDiscovered: 1957,
    electronsPerShell: [2, 8, 18, 32, 32, 8, 2],
  },
  {
    element: "Lr",
    name: "Lawrencium",
    atomicNumber: 103,
    atomicMass: 266,
    group: "",
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Lr",
    electronConfig: "[Rn] 5f14 6d1 7s2",
    electronegativity: 1.3,
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 470,
    electronAffinity: "",
    oxidationStates: 3,
    standardState: "",
    bondingType: "",
    meltingPoint: 1900,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1961,
    electronsPerShell: [2, 8, 18, 32, 32, 8, 3],
  },
  {
    element: "Rf",
    name: "Rutherfordium",
    atomicNumber: 104,
    atomicMass: 267,
    group: 4,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Rf",
    electronConfig: "[Rn] 5f14 6d2 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1969,
    electronsPerShell: [2, 8, 18, 32, 32, 10, 2],
  },
  {
    element: "Db",
    name: "Dubnium",
    atomicNumber: 105,
    atomicMass: 268,
    group: 5,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Db",
    electronConfig: "[Rn] 5f14 6d3 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1967,
    electronsPerShell: [2, 8, 18, 32, 32, 11, 2],
  },
  {
    element: "Sg",
    name: "Seaborgium",
    atomicNumber: 106,
    atomicMass: 271,
    group: 6,
    period: 7,
    block: "d",

    state: "solid",
    symbol: "Sg",
    electronConfig: "[Rn] 5f14 6d4 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",

    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1974,

    electronsPerShell: [2, 8, 18, 32, 32, 12, 2],
  },
  {
    element: "Bh",
    name: "Bohrium",
    atomicNumber: 107,
    atomicMass: 272,
    group: 7,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Bh",

    electronConfig: "[Rn] 5f14 6d5 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",

    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1976,

    electronsPerShell: [2, 8, 18, 32, 32, 13, 2],
  },
  {
    element: "Hs",
    name: "Hassium",
    atomicNumber: 108,
    atomicMass: 270,
    group: 8,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Hs",

    electronConfig: "[Rn] 5f14 6d6 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",

    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1984,

    electronsPerShell: [2, 8, 18, 32, 32, 14, 2],
  },
  {
    element: "Mt",
    name: "Meitnerium",
    atomicNumber: 109,
    atomicMass: 276,
    group: 9,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Mt",

    electronConfig: "[Rn] 5f14 6d7 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",

    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1982,

    electronsPerShell: [2, 8, 18, 32, 32, 15, 2],
  },
  {
    element: "Ds",
    name: "Darmstadtium",
    atomicNumber: 110,
    atomicMass: 281,
    group: 10,

    period: 7,
    block: "d",
    state: "solid",
    symbol: "Ds",

    electronConfig: "[Rn] 5f14 6d9 7s1",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",

    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1994,

    electronsPerShell: [2, 8, 18, 32, 32, 17, 1],
  },
  {
    element: "Rg",
    name: "Roentgenium",
    atomicNumber: 111,
    atomicMass: 280,
    group: 11,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Rg",
    electronConfig: "[Rn] 5f14 6d10 7s1",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: 580,
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1994,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 1],
  },
  {
    element: "Cn",
    name: "Copernicium",
    atomicNumber: 112,
    atomicMass: 285,
    group: 12,
    period: 7,
    block: "d",
    state: "solid",
    symbol: "Cn",
    electronConfig: "[Rn] 5f14 6d10 7s2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "transition metal",
    yearDiscovered: 1996,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 2],
  },
  {
    element: "Nh",
    name: "Nihonium",
    atomicNumber: 113,
    atomicMass: 284,
    group: 13,
    period: 7,
    block: "p",
    state: "solid",
    symbol: "Nh",
    electronConfig: "[Rn] 5f14 6d10 7s2 7p1",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "post-transition metal",
    yearDiscovered: 2003,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 3],
  },
  {
    element: "Fl",
    name: "Flerovium",
    atomicNumber: 114,
    atomicMass: 289,
    group: 14,
    period: 7,
    block: "p",
    state: "solid",
    symbol: "Fl",
    electronConfig: "[Rn] 5f14 6d10 7s2 7p2",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: 2400,
    boilingPoint: "",
    density: "",
    groupBlock: "post-transition metal",
    yearDiscovered: 1998,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 4],
  },
  {
    element: "Mc",
    name: "Moscovium",
    atomicNumber: 115,
    atomicMass: 288,
    group: 15,
    period: 7,
    block: "p",
    state: "solid",
    symbol: "Mc",
    electronConfig: "[Rn] 5f14 6d10 7s2 7p3",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: "",
    boilingPoint: "",
    density: "",
    groupBlock: "post-transition metal",
    yearDiscovered: 2003,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 5],
  },
  {
    element: "Lv",
    name: "Livermorium",
    atomicNumber: 116,
    atomicMass: 293,
    group: 16,
    period: 7,
    block: "p",
    state: "solid",
    symbol: "Lv",
    electronConfig: "[Rn] 5f14 6d10 7s2 7p4",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: "",
    boilingPoint: "",
    density: "",
    groupBlock: "post-transition metal",
    yearDiscovered: 2000,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 6],
  },
  {
    element: "Ts",
    name: "Tennessine",
    atomicNumber: 117,
    atomicMass: 294,
    group: 17,
    period: 7,
    block: "p",
    state: "solid",
    symbol: "Ts",
    electronConfig: "[Rn] 5f14 6d10 7s2 7p5",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: "",
    boilingPoint: "",
    density: "",
    groupBlock: "halogen",
    yearDiscovered: 2010,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 7],
  },
  {
    element: "Og",
    name: "Oganesson",
    atomicNumber: 118,
    atomicMass: 294,
    group: 18,
    period: 7,
    block: "p",
    state: "solid",
    symbol: "Og",
    electronConfig: "[Rn] 5f14 6d10 7s2 7p6",
    electronegativity: "",
    atomicRadius: "",
    ionRadius: "",
    vanDelWaalsRadius: "",
    ionizationEnergy: "",
    electronAffinity: "",
    oxidationStates: "",
    standardState: "",
    bondingType: "",
    meltingPoint: "",
    boilingPoint: "",
    density: "",
    groupBlock: "noble gas",
    yearDiscovered: 2002,
    electronsPerShell: [2, 8, 18, 32, 32, 18, 8],
  },
];
